export const quizState = {
  isPlayQuestion: false,
  isPlayAnswer: false,
  questionAudioCurrentTime: 0,
  answerAudioCurrentTime: 0,
  answersArr: [],
  isGuessed: false,
  songId: 0,
  questionNum: 1,
  currPoints: 5,
  scoreArr: [],
  totalScore: 0,
  maxScore: 0,
  question: 0,
  questionAudioVolume: 0.5,
  answerAudioVolume: 0.5,
  questionAudioDuration: 0,
  isClickableAnswer: false,
}